const os = require('os');
const path = require('path');

const SESSION_ROOT = path.join(os.homedir(), '.codex', 'sessions');
const AUTH_PATH = path.join(os.homedir(), '.codex', 'auth.json');
const TAIL_BYTES = 1024 * 1024;
const HEAD_BYTES = 64 * 1024;
const ACTIVE_SESSION_MS = 10 * 60 * 1000;
const GLOBAL_SCAN_LIMIT = 8;
const AUTH_MISSING_GRACE_MS = 3000;
const AUTH_WATCH_DEBOUNCE_MS = 750;
const SWITCH_ACCOUNT_GUARD_MS = 5 * 60 * 1000;

const ACCOUNT_PROFILES_KEY = 'accountProfiles';
const MAX_ACCOUNT_PROFILES = 10;
const ACTIVE_ACCOUNT_KEY = 'activeAccountKey';
const ACTIVE_ACCOUNT_SINCE_KEY = 'activeAccountSince';
const LEGACY_ACTIVE_ACCOUNT_ID_KEY = 'activeAccountId';
const ACCOUNT_SECRET_PREFIX = 'codexGestion.account.';
const PROJECT_CONTEXT_DIR = '.codex-gestion';
const PROJECT_CONTEXT_FILE = 'PROJECT_CONTEXT.md';
const PROJECT_CONTEXT_START = '<!-- CODEX_LOCAL_STATS:AUTO_START -->';
const PROJECT_CONTEXT_END = '<!-- CODEX_LOCAL_STATS:AUTO_END -->';

const AUTH_CHECK_TIMEOUT_MS = 15000;
const LOGIN_WATCH_TIMEOUT_MS = 10 * 60 * 1000;
const AUTH_STATUS_MAX_AGE_MS = 5 * 60 * 1000;
const CODEX_REOPEN_DELAY_MS = 400;
const POST_SWITCH_REFRESH_DELAYS_MS = [2000, 10000, 30000];
const CODEX_EXECUTABLE_NAMES = process.platform === 'win32'
  ? ['codex.exe', 'codex.cmd', 'codex.bat', 'codex']
  : ['codex'];

module.exports = {
  ACCOUNT_PROFILES_KEY,
  ACCOUNT_SECRET_PREFIX,
  ACTIVE_ACCOUNT_KEY,
  ACTIVE_ACCOUNT_SINCE_KEY,
  ACTIVE_SESSION_MS,
  AUTH_CHECK_TIMEOUT_MS,
  AUTH_MISSING_GRACE_MS,
  AUTH_PATH,
  AUTH_STATUS_MAX_AGE_MS,
  AUTH_WATCH_DEBOUNCE_MS,
  CODEX_EXECUTABLE_NAMES,
  CODEX_REOPEN_DELAY_MS,
  GLOBAL_SCAN_LIMIT,
  HEAD_BYTES,
  LEGACY_ACTIVE_ACCOUNT_ID_KEY,
  LOGIN_WATCH_TIMEOUT_MS,
  MAX_ACCOUNT_PROFILES,
  POST_SWITCH_REFRESH_DELAYS_MS,
  PROJECT_CONTEXT_DIR,
  PROJECT_CONTEXT_END,
  PROJECT_CONTEXT_FILE,
  PROJECT_CONTEXT_START,
  SESSION_ROOT,
  SWITCH_ACCOUNT_GUARD_MS,
  TAIL_BYTES
};